services:
  - type: web
    name: mangaview
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        fromService:
          type: web
          name: mangaview
          property: host
          
      # Users database connection
      - key: USERS_DB_HOST
        fromService:
          name: mangaview-users-db
          type: pserv
          property: host
      - key: USERS_DB_PORT
        fromService:
          name: mangaview-users-db
          type: pserv
          property: port
      - key: USERS_DB_DATABASE
        fromService:
          name: mangaview-users-db
          type: pserv
          property: database
      - key: USERS_DB_USERNAME
        fromService:
          name: mangaview-users-db
          type: pserv
          property: user
      - key: USERS_DB_PASSWORD
        fromService:
          name: mangaview-users-db
          type: pserv
          property: password
          
      # Manga database connection
      - key: MANGA_DB_HOST
        fromService:
          name: mangaview-manga-db
          type: pserv
          property: host
      - key: MANGA_DB_PORT
        fromService:
          name: mangaview-manga-db
          type: pserv
          property: port
      - key: MANGA_DB_DATABASE
        fromService:
          name: mangaview-manga-db
          type: pserv
          property: database
      - key: MANGA_DB_USERNAME
        fromService:
          name: mangaview-manga-db
          type: pserv
          property: user
      - key: MANGA_DB_PASSWORD
        fromService:
          name: mangaview-manga-db
          type: pserv
          property: password
          
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
    healthCheckPath: /
    buildCommand: ""
    startCommand: ""

  # Users database service
  - type: pserv
    name: mangaview-users-db
    plan: free
    env: docker
    disk:
      name: users-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Manga database service
  - type: pserv
    name: mangaview-manga-db
    plan: free
    env: docker
    disk:
      name: manga-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
